name: jeevan
description: "Jeevan is a premium AI-powered automotive safety application designed to provide life-saving assistance and peace of mind on every journey."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  latlong2: 0.9.1
  flutter_map: ^8.0.0
  flutter_animate: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  remove_alpha_ios: true
